### PR TITLE
Install nvidia DKMS if using driver currently

### PR DESCRIPTION
**Pull request by Doty1154**
This is intended to install the latest version of the NVIDIA driver assuming the user already installed the latest version of the Ubuntu NVIDIA driver.

### CODE REVIEW

**Comment by damentz** [comment]
I don't agree with this, the Liquorix install script shouldn't be managing other packages unless they're required to install Liquorix at all (dependencies or prerequisites to running the script).

This also quickly goes down the slippery slope that we need to have an nvidia install script for Arch, Debian, and Ubuntu (they all have their own solutions).

Closing without merging.

**Comment by Doty1154** [comment]
@damentz By default the install of your kernel leaves the user unbootable machine if they have a nvidia card & using the distros available propriety drivers.  I feel like that leaves a bad first experience in peoples mouth.. 
Could the website at least state something to the extent of "by default this kernel doesn't come with propriety gpu drivers if you wish to use your nvidia gpu be sure to install the nvidia dkms modules available from your distro"

**Comment by damentz** [comment]
The issue of out of tree modules not working with a new kernel is well understood.  It's also one of those problems that if the person installing Liquorix can't figure out, there's a good chance they're out of their depth for other reasons.

Liquorix started initially as a kernel that was difficult to install by design.  It's only recently that it's been made streamlined through the install script.  This reduces the barrier of entry to those that are capable of copying the script on the site to their terminal and run it.

This does not however solve any of the other problems around running a custom kernel, which includes the persons ability to troubleshoot and navigate through issues on their system.  Adding a disclaimer, in my opinion, won't change much since the problem audience are the ones installing Liquorix that are not reading warnings, disclaimers, terminal output, etc.

Going back to the script, the slippery slope I was referring to is about taking responsibility of getting nvidia working away from the user.  To do this properly will require a lot of testing.  Unfortunately (or fortunately?), I don't have any more nvidia devices (because of this problem), so I won't be able to test my own scripts.  This puts me in a situation where I'm responsible for getting nvidia working without the ability to verify if my scripts work.

An attempt at making a universal install script has already been made, and the script is 11k lines: https://github.com/smxi/sgfxi/blob/master/sgfxi.  To implement a fraction of its functionality correctly is impossible, and I'll always be chasing the latest quirk.  Not to mention, what if the script causes the opposite to happen?  What if this management of nvidia packages actually ends up breaking setups instead of fixing them?  This is not something I'm going to get involved in.

If you want more information, you can ask my good friend maintaining **sgfxi**: @smxi

**Comment by smxi** [comment]
Just to be clear, the above language is EXACTLY what is wrong with trying to cater to newbie users.

It's false to state that not making the absolutely impossible requirement that current liquorix should support nvidia non free driver is harmful to users in any way. This idea is absolutely absurd if you have any experience at all with non free nvidia driver (and even worse, the old AMD fglrx driver). 

Non free drivers can't be 'supported' for the absolutely basic reason that they are non free drivers, you have zero control if they support current kernel ABI, which can, and does, break nvidia, and any other non free driver, at any time, without being able to predict when such breaks are created. The same goes for Xorg support, which is also not a given, though that's less extreme today because Xorg development has slowed so much.

As the person who suffered trying to support, with patches etc, current kernels in sgfxi for far too long, I can state that nobody who knows what they are talking about would ever believe this is a desirable goal, or even possible. Yes, often nvdia current, or nvidia beta next, will support new kernels, unless they don't. And that's not even getting into the legacy drivers nvidia also ships, but with FAR fewer and FAR less frequent updates and new kernel support.

damentz not only should not consider such an absurd idea, he'd be crazy to do so, for the very clear reasons he stated.

I used to do that testing always, and I will NEVER do it again, it's a horrible way to spend your time and life, and it's stupid, to make it even worse. The real solution to running free current kernels is to use free drivers, or to use non free packaged nvidia driver coupled with stable kernel, which is also a good solution.

But this is all besides the point, because this statement: 

> it leaves the user with an unbootable machine

as the precise reason you do NOT want to try to cater to newbie users with a current linux kernel, current as in roughly tracking, or trailing slightly, linux latest. Why? Because then you have to try to support users who don't know the difference between Xorg starting and your computer booting. Any user who doesn't know that difference should either switch to intel/amd graphics device, with free drivers, which are part of the kernel, and thus, track the kernel by definition, or not use Liquorix. 

To be clear, you are NOT left with an unbootable machine, you are left with a machine that boots absolutely fine, but where Xorg fails to start, leaving a generally black screen, which can readily be escaped by anyone who knows what they are doing using ctrl alt F1-6, and logging into their shell. To me this is the exact problem with trying to make things too easy on newbie users who should not be using such kernels, they should be using the absolutely fine and stable distro kernels that ubuntu or debian package, in the case of those. 

Even distros that package nvidia and current kernels, like Arch, and who do very good work tracking and patching nvidia, cannot do anything at all to help with legacy nvidia devices (and legacy is a technical term here, it means a graphic device not supported by current stable nvidia driver), and can only sometimes find and apply patches to create workarounds for nvidia for the current kernel. But even that is hit and miss over time, because sometimes those patches are not actually all that stable, yes, they let xorg start, but may be unstable and unreliable. 

Further, my tests with nouveau, which I tried before getting rid of all my nvidia devices, and switching to AMD graphics, showed it was extremely unstable, and that was for older nvidia graphics devices, not cutting edge ones, where it's largely hopeless. I tried it a few weeks, and finally gave up, it wasn't worth it.

And this doesn't even touch on nvidia and wayland, which is as of now, a nonstarter unless you use nouveau. This is slowly changing for nvidia graphics of Turing or newer vintage, which are implementing a kernel wrapper that will be 'free', though only in a purely technical sense, what it actually does is move all the non free code to the card itself, and the wrapper basically just talks to that new interface, but it will create the basic reality of being able to use 'free' nvidia drivers, which will then support DRM and KMS which means wayland should work, but this is in the future, that's still in beta mode testing, and will never support older nvidia graphics devices, the legacy ones that is once the next legacy drivers are released, which will be pre-turing.

Trying to do such cross distro support is insane, I used to do it for a while, supported fedora, debian, ubuntu, and arch, but that is constant work and churn, and the solution requires as damentz noted, about 10k+ lines of code, but worse, it requires constant and never ceasing effort, chasing down patches, etc, but that's not really the worst part, the worst part is it's a non free driver, and you will ALWAYS hit a point where there is no patch, the driver fails on the latest kernel, or the patch is unstable, and you are left with no working nvidia for current kernel.

I heartily approve of, and endorse, damentz rejecting this awful idea, and don't even need to look at the patch because honestly, if someone doesn't know the difference between nvidia failing to load and run xorg and the kernel failing to boot,  there is essentially zero chance that they actually understand what is involved in trying to get something like this working over time.

And I'm ignoring the terrible non free driver packages, that fail to do everything they needed to do, like disable nomodesetting if installing non free, or enabling it if installing free. Even sgfxi has bugs I don't care to figure out with this logic, though it used to work, but I don't use nvidia cards anymore so I can't really test it, nor do I feel like doing it, nor would I volunteer anyone else to take on that fairly ridiculous task.

It's easy to make one single incomplete patch that covers one single case, and fails to cover ALL others (again, I don't even have to look at the patch, I know already what it fails to do because all distro packaged drivers fail to do iti), it's quite another to take on this task over 10 years, year in and year out, which is basically what you are volunteering damentz for. Since I know better, I wouldn't  do it for any amount of money (ok, I lied, pay me professional rates to do it, and I'll do it, but only then, and you can't afford that).

Closing this is the correct action.

**Pull request closed without merging**
